# Project : Evaluate Cars Condition based on given feature


- buying	Feature	Categorical		buying price	
- maint	Feature	Categorical		price of the maintenance	
- doors	Feature	Categorical		number of doors	
- persons	Feature	Categorical		capacity in terms of persons to carry		
- lug_boot	Feature	Categorical		the size of luggage boot		
- safety	Feature	Categorical		estimated safety of the car		
- class	Target	Categorical		evaulation level (unacceptable, acceptable, good, very good)	


##### based on this feature predict the car condition

### Step 1: Import Dependencies 

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn import tree
from sklearn.preprocessing import (LabelEncoder, 
                                   StandardScaler, 
                                   MinMaxScaler)

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import (confusion_matrix, 
                             accuracy_score,
                             classification_report)

### Step 2: Load Dataset 

In [2]:
df = pd.read_csv(r"cars.csv", header=None)
df.columns=['buying','maint','doors','persons','lug_boot','safety','classes']
df.head()

,buying,maint,doors,persons,lug_boot,safety,classes
0,vhigh,vhigh,2,2,small,low,unacc
1,vhigh,vhigh,2,2,small,med,unacc
2,vhigh,vhigh,2,2,small,high,unacc
3,vhigh,vhigh,2,2,med,low,unacc
4,vhigh,vhigh,2,2,med,med,unacc


In [3]:
df.shape

(1728, 7)

In [4]:
# check category level of all columns
for col in df.columns:
    print("----------------{}-----------------------".format(col))
    print(df[col].value_counts())
    print()

----------------buying-----------------------
buying
vhigh    432
high     432
med      432
low      432
Name: count, dtype: int64

----------------maint-----------------------
maint
vhigh    432
high     432
med      432
low      432
Name: count, dtype: int64

----------------doors-----------------------
doors
2        432
3        432
4        432
5more    432
Name: count, dtype: int64

----------------persons-----------------------
persons
2       576
4       576
more    576
Name: count, dtype: int64

----------------lug_boot-----------------------
lug_boot
small    576
med      576
big      576
Name: count, dtype: int64

----------------safety-----------------------
safety
low     576
med     576
high    576
Name: count, dtype: int64

----------------classes-----------------------
classes
unacc    1210
acc       384
good       69
vgood      65
Name: count, dtype: int64



in the above values counts we can see in two column we have category and numbers so we need to replace the categories with numbers using label encoder 

### Step 3: Data Preprocessing

In [5]:
# check missing values
df.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

in the above data we can see there is no missing values 

In [6]:
# check basic info 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   buying    1728 non-null   object
 1   maint     1728 non-null   object
 2   doors     1728 non-null   object
 3   persons   1728 non-null   object
 4   lug_boot  1728 non-null   object
 5   safety    1728 non-null   object
 6   classes   1728 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


we need to perform label encoder on all the columns bcoz all the columns contain object data type

In [7]:
# apply label encoder to convert categories into numeric values
le = LabelEncoder()

for x in df.columns:
    
    print(x)
    df[x]=le.fit_transform(df[x])
    le_name = dict(zip(le.classes_, le.transform(le.classes_)))
    print("--------------------------------------------------")
    print("Feature: ", x)
    print("Mapping: ", le_name)    

buying
--------------------------------------------------
Feature:  buying
Mapping:  {'high': 0, 'low': 1, 'med': 2, 'vhigh': 3}
maint
--------------------------------------------------
Feature:  maint
Mapping:  {'high': 0, 'low': 1, 'med': 2, 'vhigh': 3}
doors
--------------------------------------------------
Feature:  doors
Mapping:  {'2': 0, '3': 1, '4': 2, '5more': 3}
persons
--------------------------------------------------
Feature:  persons
Mapping:  {'2': 0, '4': 1, 'more': 2}
lug_boot
--------------------------------------------------
Feature:  lug_boot
Mapping:  {'big': 0, 'med': 1, 'small': 2}
safety
--------------------------------------------------
Feature:  safety
Mapping:  {'high': 0, 'low': 1, 'med': 2}
classes
--------------------------------------------------
Feature:  classes
Mapping:  {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}


In [8]:
df.head()

,buying,maint,doors,persons,lug_boot,safety,classes
0,3,3,0,0,2,1,2
1,3,3,0,0,2,2,2
2,3,3,0,0,2,0,2
3,3,3,0,0,1,1,2
4,3,3,0,0,1,2,2


### Step 4: Seprate X and y

In [9]:
df.columns

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'classes'], dtype='object')

In [ ]:
# # USING FEATURE NAME FOR X AND Y 
# X = df[['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety']]
# y = df["classes"]

In [10]:
X = df.iloc[  :  ,  :-1]  # independent variables
y = df.iloc[  :  ,   -1]  # dependent variable

### Step 5: Data Spliting 

In [11]:
# Split the data into test and train
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.3,
                                                    random_state=10)  
# verify spliting data
print("Total Data: ", df.shape)
print("Train X: ", X_train.shape)
print("Train y: ", y_train.shape)
print("Test X: ", X_test.shape)
print("Test y: ", y_test.shape)

Total Data:  (1728, 7)
Train X:  (1209, 6)
Train y:  (1209,)
Test X:  (519, 6)
Test y:  (519,)


### Step 6: Data Normalisation

In [12]:
# perform data normalisation

# create object for scaler
scaler = MinMaxScaler()

# fit the train data on scaler object 
scaler.fit(X_train)

X_train_scale = scaler.transform(X_train)
X_test_scale = scaler.transform(X_test)

Note: In this data set we can see all the values from all the columns and rows are ranging from 0 to 5 so there is no extreme high and low values so thats why we dont need to perfom standardsiation and normalisation

In [13]:
# compare normal and scale data
print(X_train.iloc[0])
print(X_train_scale[0])

buying      0
maint       0
doors       1
persons     2
lug_boot    0
safety      0
Name: 593, dtype: int32
[0.         0.         0.33333333 1.         0.         0.        ]


### Step 7: Build Model

#### 1. Decision Tree 

In [14]:
# create model object  with default parameter 
model_dt = DecisionTreeClassifier()

# create model object  with custom parameter 
model_dt = DecisionTreeClassifier(criterion='gini',
                                  random_state=10, 
                                  min_samples_leaf=5, 
                                  min_samples_split=20,
                                  max_leaf_nodes=15,
                                  max_depth=6)

#fit the model on the data and predict the values
model_dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [15]:
model_dt.get_depth()

14

In [16]:
# prediction on Test Data
y_pred= model_dt.predict(X_test)

# print(list(zip(y_test,y_pred)))

In [17]:
# confusion matrix  {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}
print("---------Confusion Matrix------------")
print(confusion_matrix(y_test, y_pred))
print()
print("---------Accuracy Score------------")
print(accuracy_score(y_test,y_pred))
print()
print("---------Classification Report------------")
print(classification_report(y_test,y_pred))

---------Confusion Matrix------------
[[ 99   2   1   0]
 [  4  17   0   0]
 [  0   0 371   0]
 [  1   0   0  24]]

---------Accuracy Score------------
0.9845857418111753

---------Classification Report------------
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       102
           1       0.89      0.81      0.85        21
           2       1.00      1.00      1.00       371
           3       1.00      0.96      0.98        25

    accuracy                           0.98       519
   macro avg       0.96      0.94      0.95       519
weighted avg       0.98      0.98      0.98       519



## Tunned Dt model


In [18]:
# criterion='gini',
# splitter='best',
# max_depth=None,
# min_samples_split=2,
# min_samples_leaf=1,
# min_weight_fraction_leaf=0.0,
# max_features=None,
# random_state=None,
# max_leaf_nodes=None,
# min_impurity_decrease=0.0,
# class_weight=None,
# ccp_alpha=0.0,

model_dt2 = DecisionTreeClassifier(criterion='gini',
                                  random_state=10, 
                                  min_samples_leaf=10, 
                                  min_samples_split=2,
                                  max_leaf_nodes=30,
                                  max_depth=6)

#fit the model on the data and predict the values
model_dt2.fit(X_train, y_train)
print("Dept: ", model_dt2.get_depth())

# prediction on Test Data
y_pred2= model_dt2.predict(X_test)

# confusion matrix  {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}
print("---------Confusion Matrix------------")
print(confusion_matrix(y_test, y_pred2))
print()
print("---------Accuracy Score------------")
print(accuracy_score(y_test,y_pred2))
print()
print("---------Classification Report------------")
print(classification_report(y_test,y_pred2))

Dept:  6
---------Confusion Matrix------------
[[ 81   0  13   8]
 [ 17   0   0   4]
 [ 19   0 352   0]
 [  0   0   0  25]]

---------Accuracy Score------------
0.882466281310212

---------Classification Report------------
              precision    recall  f1-score   support

           0       0.69      0.79      0.74       102
           1       0.00      0.00      0.00        21
           2       0.96      0.95      0.96       371
           3       0.68      1.00      0.81        25

    accuracy                           0.88       519
   macro avg       0.58      0.69      0.63       519
weighted avg       0.86      0.88      0.87       519



C:\Users\Dev\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Dev\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Dev\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# feature importance for all columns
# total will be 1 

print(list(zip(df.columns, model_dt.feature_importances_)))

In [ ]:
# from sklearn import tree
# import graphviz

# with open("model_DecisionTree.txt", "w") as f:
#     f = tree.export_graphviz(model_dt, feature_names=cars_df.columns[:-1], out_file=f)
    
# # generate the file and upload the code in webgraphviz.com to plot the decision tree

In [ ]:
df.columns[:-1]

In [ ]:
%%time

# it will take 5 to 6 mins to create image so wait.....
fig = plt.figure(figsize=(45,60)) 
dot_data = tree.plot_tree(model_dt, 
                   feature_names=list(df.columns[:-1]),  
                   class_names=list(df.columns[-1]),
                   filled=True)
plt.savefig("base_model1.jpeg")

In [ ]:
%%time

# it will take 5 to 6 mins to create image so wait.....
fig = plt.figure(figsize=(45,60)) 
dot_data = tree.plot_tree(model_dt2, 
                   feature_names=list(df.columns[:-1]),  
                   class_names=list(df.columns[-1]),
                   filled=True)
plt.savefig("tuned_model1.jpeg")

#### 2.  USING SVM

In [20]:
from sklearn import svm

In [22]:
# create svm object 
svc_model = svm.SVC()

# train svm model on train dataset
svc_model.fit(X_train, y_train)

# predict on test dataset
y_pred=svc_model.predict(X_test)

In [23]:
# confusion matrix  {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}
print("---------Confusion Matrix------------")
print(confusion_matrix(y_test, y_pred))
print()
print("---------Accuracy Score------------")
print(accuracy_score(y_test,y_pred))
print()
print("---------Classification Report------------")
print(classification_report(y_test,y_pred))

---------Confusion Matrix------------
[[ 74   0  28   0]
 [ 14   5   0   2]
 [  4   0 367   0]
 [  6   0   0  19]]

---------Accuracy Score------------
0.8959537572254336

---------Classification Report------------
              precision    recall  f1-score   support

           0       0.76      0.73      0.74       102
           1       1.00      0.24      0.38        21
           2       0.93      0.99      0.96       371
           3       0.90      0.76      0.83        25

    accuracy                           0.90       519
   macro avg       0.90      0.68      0.73       519
weighted avg       0.90      0.90      0.89       519



In [27]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
car_evaluation = fetch_ucirepo(id=19) 
  
# data (as pandas dataframes) 
X = car_evaluation.data.features 
y = car_evaluation.data.targets 
  
# metadata 
print(car_evaluation.metadata) 
  
# variable information 
print(car_evaluation.variables) 

{'uci_id': 19, 'name': 'Car Evaluation', 'repository_url': 'https://archive.ics.uci.edu/dataset/19/car+evaluation', 'data_url': 'https://archive.ics.uci.edu/static/public/19/data.csv', 'abstract': 'Derived from simple hierarchical decision model, this database may be useful for testing constructive induction and structure discovery methods.', 'area': 'Other', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 1728, 'num_features': 6, 'feature_types': ['Categorical'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1988, 'last_updated': 'Thu Aug 10 2023', 'dataset_doi': '10.24432/C5JP48', 'creators': ['Marko Bohanec'], 'intro_paper': {'ID': 249, 'type': 'NATIVE', 'title': 'Knowledge acquisition and explanation for multi-attribute decision making', 'authors': 'M. Bohanec, V. Rajkovič', 'venue': '8th Intl Workshop on Expert Systems and their Applications, 

In [ ]:
X = df[['sepal length', 'sepal width', 'petal length', 'petal width']]
y = df.Label

# Split the data into test and train
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.3,
                                                    random_state=10)  

model_dt3 = DecisionTreeClassifier()

#fit the model on the data and predict the values
model_dt3.fit(X_train, y_train)
print("Dept: ", model_dt3.get_depth())

# prediction on Test Data
y_pred3= model_dt3.predict(X_test)

# confusion matrix  {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}
print("---------Confusion Matrix------------")
print(confusion_matrix(y_test, y_pred3))
print()
print("---------Accuracy Score------------")
print(accuracy_score(y_test,y_pred3))
print()
print("---------Classification Report------------")
print(classification_report(y_test,y_pred3))

In [ ]:
%%time

# it will take 5 to 6 mins to create image so wait.....
fig = plt.figure(figsize=(45,60)) 
dot_data = tree.plot_tree(model_dt3, 
                   feature_names=list(df.columns[:-1]),  
                   class_names=list(df.columns[-1]),
                   filled=True)
plt.savefig("tuned_model3.jpeg")

# Bagging Approach 

**Running Bagging Classifier model**

In [24]:
from sklearn.ensemble import BaggingClassifier

In [25]:
#predicting using the Bagging_Classifier
model = BaggingClassifier(n_estimators=50, random_state=10) 

# try to increase the n_estimator  # min_samples_leaf=1, max_depth=None

#fit the model on the data and predict the values
model = model.fit(X_train,y_train)

y_pred=model.predict(X_test)


In [26]:
# confusion matrix  {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}
print("---------Confusion Matrix------------")
print(confusion_matrix(y_test, y_pred))
print()
print("---------Accuracy Score------------")
print(accuracy_score(y_test,y_pred))
print()
print("---------Classification Report------------")
print(classification_report(y_test,y_pred))

---------Confusion Matrix------------
[[102   0   0   0]
 [  1  20   0   0]
 [  2   0 369   0]
 [  1   0   0  24]]

---------Accuracy Score------------
0.9922928709055877

---------Classification Report------------
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       102
           1       1.00      0.95      0.98        21
           2       1.00      0.99      1.00       371
           3       1.00      0.96      0.98        25

    accuracy                           0.99       519
   macro avg       0.99      0.98      0.98       519
weighted avg       0.99      0.99      0.99       519



**Running Random Forest model**

In [30]:
from sklearn.ensemble import RandomForestClassifier

In [45]:
%%time 

#predicting using the Random_Forest_Classifier
model_rf = RandomForestClassifier(n_estimators=100, 
                                          random_state=10,
                                         verbose=0,
                                        n_jobs=-1)

#fit the model on the data and predict the values
model_rf.fit(X_train,y_train)

y_pred = model_rf.predict(X_test)

CPU times: total: 62.5 ms
Wall time: 331 ms


In [46]:
# confusion matrix  {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}
print("---------Confusion Matrix------------")
print(confusion_matrix(y_test, y_pred))
print()
print("---------Accuracy Score------------")
print(accuracy_score(y_test,y_pred))
print()
print("---------Classification Report------------")
print(classification_report(y_test,y_pred))

---------Confusion Matrix------------
[[ 99   3   0   0]
 [  3  18   0   0]
 [  2   0 369   0]
 [  2   0   0  23]]

---------Accuracy Score------------
0.9807321772639692

---------Classification Report------------
              precision    recall  f1-score   support

           0       0.93      0.97      0.95       102
           1       0.86      0.86      0.86        21
           2       1.00      0.99      1.00       371
           3       1.00      0.92      0.96        25

    accuracy                           0.98       519
   macro avg       0.95      0.94      0.94       519
weighted avg       0.98      0.98      0.98       519



# Boosting Classifier

**Running Adaboost classifier**

In [47]:
from sklearn.ensemble import AdaBoostClassifier

In [50]:
#predicting using the AdaBoost_Classifier
model_AdaBoost=AdaBoostClassifier(base_estimator=DecisionTreeClassifier(random_state=10),
                                 n_estimators=90)

#fit the model on the data and predict the values
model_AdaBoost.fit(X_train,y_train)

y_pred=model_AdaBoost.predict(X_test)


C:\Users\Dev\anaconda3\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


In [51]:
# confusion matrix  {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}
print("---------Confusion Matrix------------")
print(confusion_matrix(y_test, y_pred))
print()
print("---------Accuracy Score------------")
print(accuracy_score(y_test,y_pred))
print()
print("---------Classification Report------------")
print(classification_report(y_test,y_pred))

---------Confusion Matrix------------
[[100   1   1   0]
 [  3  18   0   0]
 [  0   0 371   0]
 [  1   0   0  24]]

---------Accuracy Score------------
0.9884393063583815

---------Classification Report------------
              precision    recall  f1-score   support

           0       0.96      0.98      0.97       102
           1       0.95      0.86      0.90        21
           2       1.00      1.00      1.00       371
           3       1.00      0.96      0.98        25

    accuracy                           0.99       519
   macro avg       0.98      0.95      0.96       519
weighted avg       0.99      0.99      0.99       519



**Running Gradient Boosting classifier**

In [52]:
from sklearn.ensemble import GradientBoostingClassifier

In [53]:
#predicting using the Gradient_Boosting_Classifier
model_GradientBoosting = GradientBoostingClassifier(n_estimators=150,
                                                     random_state=10)

#fit the model on the data and predict the values
model_GradientBoosting.fit(X_train,y_train)

y_pred=model_GradientBoosting.predict(X_test)

In [54]:
# confusion matrix  {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}
print("---------Confusion Matrix------------")
print(confusion_matrix(y_test, y_pred))
print()
print("---------Accuracy Score------------")
print(accuracy_score(y_test,y_pred))
print()
print("---------Classification Report------------")
print(classification_report(y_test,y_pred))

---------Confusion Matrix------------
[[101   1   0   0]
 [  0  21   0   0]
 [  0   0 371   0]
 [  0   0   0  25]]

---------Accuracy Score------------
0.9980732177263969

---------Classification Report------------
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       102
           1       0.95      1.00      0.98        21
           2       1.00      1.00      1.00       371
           3       1.00      1.00      1.00        25

    accuracy                           1.00       519
   macro avg       0.99      1.00      0.99       519
weighted avg       1.00      1.00      1.00       519



# Catboost 

In [ ]:
# pip install catboost

In [55]:
from catboost import CatBoostClassifier

In [56]:
#predicting using the Gradient_Boosting_Classifier
model_GradientBoosting = CatBoostClassifier()

#fit the model on the data and predict the values
model_GradientBoosting.fit(X_train,y_train)

y_pred=model_GradientBoosting.predict(X_test)

Learning rate set to 0.079896
0:	learn: 1.2681340	total: 150ms	remaining: 2m 29s
1:	learn: 1.1800890	total: 151ms	remaining: 1m 15s
2:	learn: 1.0905759	total: 151ms	remaining: 50.3s
3:	learn: 1.0106046	total: 152ms	remaining: 37.9s
4:	learn: 0.9450573	total: 153ms	remaining: 30.4s
5:	learn: 0.8966915	total: 154ms	remaining: 25.5s
6:	learn: 0.8501689	total: 156ms	remaining: 22.1s
7:	learn: 0.7972903	total: 158ms	remaining: 19.6s
8:	learn: 0.7614882	total: 159ms	remaining: 17.5s
9:	learn: 0.7260354	total: 160ms	remaining: 15.8s
10:	learn: 0.6962340	total: 161ms	remaining: 14.4s
11:	learn: 0.6669178	total: 161ms	remaining: 13.3s
12:	learn: 0.6322237	total: 162ms	remaining: 12.3s
13:	learn: 0.6083418	total: 163ms	remaining: 11.5s
14:	learn: 0.5857253	total: 164ms	remaining: 10.8s
15:	learn: 0.5625754	total: 165ms	remaining: 10.2s
16:	learn: 0.5393360	total: 166ms	remaining: 9.61s
17:	learn: 0.5193320	total: 167ms	remaining: 9.12s
18:	learn: 0.5045812	total: 168ms	remaining: 8.67s
19:	learn

235:	learn: 0.0541549	total: 372ms	remaining: 1.21s
236:	learn: 0.0538485	total: 373ms	remaining: 1.2s
237:	learn: 0.0534852	total: 374ms	remaining: 1.2s
238:	learn: 0.0533093	total: 375ms	remaining: 1.19s
239:	learn: 0.0529996	total: 376ms	remaining: 1.19s
240:	learn: 0.0527068	total: 377ms	remaining: 1.19s
241:	learn: 0.0525554	total: 378ms	remaining: 1.18s
242:	learn: 0.0524041	total: 379ms	remaining: 1.18s
243:	learn: 0.0521992	total: 380ms	remaining: 1.18s
244:	learn: 0.0518007	total: 381ms	remaining: 1.17s
245:	learn: 0.0516320	total: 382ms	remaining: 1.17s
246:	learn: 0.0513362	total: 383ms	remaining: 1.17s
247:	learn: 0.0510797	total: 385ms	remaining: 1.17s
248:	learn: 0.0509277	total: 386ms	remaining: 1.16s
249:	learn: 0.0507731	total: 387ms	remaining: 1.16s
250:	learn: 0.0504726	total: 388ms	remaining: 1.16s
251:	learn: 0.0502573	total: 389ms	remaining: 1.16s
252:	learn: 0.0500536	total: 390ms	remaining: 1.15s
253:	learn: 0.0496723	total: 391ms	remaining: 1.15s
254:	learn: 0.

411:	learn: 0.0283771	total: 555ms	remaining: 793ms
412:	learn: 0.0282422	total: 556ms	remaining: 791ms
413:	learn: 0.0282055	total: 557ms	remaining: 789ms
414:	learn: 0.0281554	total: 559ms	remaining: 787ms
415:	learn: 0.0280134	total: 560ms	remaining: 786ms
416:	learn: 0.0279312	total: 561ms	remaining: 784ms
417:	learn: 0.0278061	total: 561ms	remaining: 782ms
418:	learn: 0.0277617	total: 562ms	remaining: 780ms
419:	learn: 0.0276749	total: 563ms	remaining: 778ms
420:	learn: 0.0276340	total: 564ms	remaining: 776ms
421:	learn: 0.0275709	total: 565ms	remaining: 774ms
422:	learn: 0.0274243	total: 566ms	remaining: 772ms
423:	learn: 0.0273240	total: 567ms	remaining: 770ms
424:	learn: 0.0272474	total: 568ms	remaining: 769ms
425:	learn: 0.0271921	total: 569ms	remaining: 767ms
426:	learn: 0.0270984	total: 570ms	remaining: 765ms
427:	learn: 0.0270121	total: 571ms	remaining: 763ms
428:	learn: 0.0269368	total: 572ms	remaining: 761ms
429:	learn: 0.0268862	total: 573ms	remaining: 759ms
430:	learn: 

599:	learn: 0.0182694	total: 740ms	remaining: 493ms
600:	learn: 0.0182232	total: 741ms	remaining: 492ms
601:	learn: 0.0181984	total: 742ms	remaining: 490ms
602:	learn: 0.0181650	total: 743ms	remaining: 489ms
603:	learn: 0.0181398	total: 744ms	remaining: 488ms
604:	learn: 0.0181111	total: 745ms	remaining: 486ms
605:	learn: 0.0180839	total: 746ms	remaining: 485ms
606:	learn: 0.0180654	total: 746ms	remaining: 483ms
607:	learn: 0.0180441	total: 747ms	remaining: 482ms
608:	learn: 0.0180084	total: 748ms	remaining: 480ms
609:	learn: 0.0179798	total: 749ms	remaining: 479ms
610:	learn: 0.0179150	total: 750ms	remaining: 478ms
611:	learn: 0.0178882	total: 751ms	remaining: 476ms
612:	learn: 0.0178717	total: 752ms	remaining: 475ms
613:	learn: 0.0178279	total: 753ms	remaining: 473ms
614:	learn: 0.0177852	total: 754ms	remaining: 472ms
615:	learn: 0.0177420	total: 755ms	remaining: 470ms
616:	learn: 0.0177003	total: 756ms	remaining: 469ms
617:	learn: 0.0176765	total: 756ms	remaining: 468ms
618:	learn: 

771:	learn: 0.0136576	total: 921ms	remaining: 272ms
772:	learn: 0.0136482	total: 923ms	remaining: 271ms
773:	learn: 0.0136366	total: 924ms	remaining: 270ms
774:	learn: 0.0136079	total: 925ms	remaining: 268ms
775:	learn: 0.0135787	total: 926ms	remaining: 267ms
776:	learn: 0.0135452	total: 927ms	remaining: 266ms
777:	learn: 0.0135295	total: 928ms	remaining: 265ms
778:	learn: 0.0135187	total: 929ms	remaining: 263ms
779:	learn: 0.0135001	total: 930ms	remaining: 262ms
780:	learn: 0.0134732	total: 931ms	remaining: 261ms
781:	learn: 0.0134522	total: 932ms	remaining: 260ms
782:	learn: 0.0134382	total: 933ms	remaining: 259ms
783:	learn: 0.0134241	total: 934ms	remaining: 257ms
784:	learn: 0.0133988	total: 935ms	remaining: 256ms
785:	learn: 0.0133802	total: 935ms	remaining: 255ms
786:	learn: 0.0133514	total: 936ms	remaining: 253ms
787:	learn: 0.0133362	total: 937ms	remaining: 252ms
788:	learn: 0.0133251	total: 939ms	remaining: 251ms
789:	learn: 0.0133045	total: 940ms	remaining: 250ms
790:	learn: 

961:	learn: 0.0105528	total: 1.1s	remaining: 43.7ms
962:	learn: 0.0105372	total: 1.11s	remaining: 42.5ms
963:	learn: 0.0105309	total: 1.11s	remaining: 41.4ms
964:	learn: 0.0105118	total: 1.11s	remaining: 40.2ms
965:	learn: 0.0104876	total: 1.11s	remaining: 39.1ms
966:	learn: 0.0104704	total: 1.11s	remaining: 37.9ms
967:	learn: 0.0104636	total: 1.11s	remaining: 36.8ms
968:	learn: 0.0104524	total: 1.11s	remaining: 35.6ms
969:	learn: 0.0104339	total: 1.11s	remaining: 34.4ms
970:	learn: 0.0104117	total: 1.11s	remaining: 33.3ms
971:	learn: 0.0104002	total: 1.11s	remaining: 32.1ms
972:	learn: 0.0103840	total: 1.12s	remaining: 31ms
973:	learn: 0.0103607	total: 1.12s	remaining: 29.8ms
974:	learn: 0.0103460	total: 1.12s	remaining: 28.7ms
975:	learn: 0.0103356	total: 1.12s	remaining: 27.5ms
976:	learn: 0.0103183	total: 1.12s	remaining: 26.4ms
977:	learn: 0.0103016	total: 1.12s	remaining: 25.3ms
978:	learn: 0.0102940	total: 1.12s	remaining: 24.1ms
979:	learn: 0.0102846	total: 1.13s	remaining: 23m

In [57]:
# confusion matrix  {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}
print("---------Confusion Matrix------------")
print(confusion_matrix(y_test, y_pred))
print()
print("---------Accuracy Score------------")
print(accuracy_score(y_test,y_pred))
print()
print("---------Classification Report------------")
print(classification_report(y_test,y_pred))

---------Confusion Matrix------------
[[101   1   0   0]
 [  0  21   0   0]
 [  0   0 371   0]
 [  0   0   0  25]]

---------Accuracy Score------------
0.9980732177263969

---------Classification Report------------
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       102
           1       0.95      1.00      0.98        21
           2       1.00      1.00      1.00       371
           3       1.00      1.00      1.00        25

    accuracy                           1.00       519
   macro avg       0.99      1.00      0.99       519
weighted avg       1.00      1.00      1.00       519



In [ ]:
pip

### Ensembel Voting Classifier 

In [58]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier

In [59]:
# create the sub models
estimators = []
model1 = DecisionTreeClassifier(criterion="gini", random_state=10)
estimators.append(('cart', model1))
model2 = SVC(kernel="rbf", C=50, gamma=0.1)
estimators.append(('svm', model2))
model3 = KNeighborsClassifier(n_neighbors=8)
estimators.append(('knn', model3))

In [60]:
estimators

[('cart', DecisionTreeClassifier(random_state=10)),
 ('svm', SVC(C=50, gamma=0.1)),
 ('knn', KNeighborsClassifier(n_neighbors=8))]

In [61]:
# create the ensemble model
ensemble = VotingClassifier(estimators)
ensemble.fit(X_train,y_train)
y_pred=ensemble.predict(X_test)
#print(Y_pred)

In [62]:
# confusion matrix  {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}
print("---------Confusion Matrix------------")
print(confusion_matrix(y_test, y_pred))
print()
print("---------Accuracy Score------------")
print(accuracy_score(y_test,y_pred))
print()
print("---------Classification Report------------")
print(classification_report(y_test,y_pred))

---------Confusion Matrix------------
[[100   0   2   0]
 [  2  19   0   0]
 [  0   0 371   0]
 [  1   0   0  24]]

---------Accuracy Score------------
0.9903660886319846

---------Classification Report------------
              precision    recall  f1-score   support

           0       0.97      0.98      0.98       102
           1       1.00      0.90      0.95        21
           2       0.99      1.00      1.00       371
           3       1.00      0.96      0.98        25

    accuracy                           0.99       519
   macro avg       0.99      0.96      0.98       519
weighted avg       0.99      0.99      0.99       519



# Conclusion 

- based on above anlysis we can that the decision tree model performs better on test data 